config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => 'registrations' }
  root 'home#index'
  mount Resque::Server.new, at: "/resque"

  namespace :api do
    namespace :v1 do
      get 'facilities',         to: 'facilities#index',          as: 'facilities', defaults: {format: :json}
      get 'facilities/:id',     to: 'facilities#show',           as: 'facility', defaults: {format: :json}
      get 'therapists',         to: 'therapists#index',          as: 'therapists', defaults: {format: :json}
      get 'therapists/:id',     to: 'therapists#show',           as: 'therapist', defaults: {format: :json}
    end
  end

  namespace :admin do
  	get 'dashboard',            to: 'dashboard#show',            as: 'dashboard'

    get 'facilities',           to: 'facilities#index',          as: 'facilities'
    post 'facilities',          to: 'facilities#import',         as: 'import_facilities'

    get 'therapists',           to: 'therapists#index',          as: 'therapists'
    get 'therapists/:id',       to: 'therapists#show',           as: 'therapist'
    post 'therapists/:id/toggle', to: 'therapists#toggle'
  end

  get  'facilities',            to: 'facilities#index',          as: 'facilities'
  get  'facilities/:id',        to: 'facilities#show',           as: 'facility'
  get  'facilities/share/:id',  to: 'facilities#share_facility', as: 'share_facility'
  post 'facilities/share',      to: 'facilities#share',          as: 'facilities_share'
  post 'facility/save/:id',     to: 'facilities#save_facility',  as: 'save_facility'
  post 'facility/remove/:id',   to: 'users#remove_facility',     as: 'remove_facility'

  get  'contact',               to: 'home#contact',              as: 'contact'
  post 'contact',               to: 'home#send_contact',         as: 'contact_us'
  get  'sign_in',               to: 'home#sign_in',              as: 'sign_in'

  get  'user',                  to: 'users#show',                as: 'user'

  get  'articles',              to: 'articles#index',            as: 'articles'
  get  'articles/share/:title', to: 'articles#show',             as: 'articles_show'
  post 'articles/share',        to: 'articles#share',            as: 'articles_share'

  get  'therapists',            to: 'therapists#index',          as: 'therapists'
  get  'therapists/new',        to: 'therapists#new',            as: 'new_therapist'
  get  'therapists/:id',        to: 'therapists#show',           as: 'therapist'
  delete 'therapists/:id',      to: 'therapists#destroy'
  get  'therapists/:id/edit',   to: 'therapists#edit',           as: 'edit_therapist'
  post 'therapist/save/:id',    to: 'therapists#save_therapist', as: 'save_therapist'
  post 'therapist/remove/:id',  to: 'users#remove_therapist',    as: 'remove_therapist'
  post 'therapists',            to: 'therapists#create'
  patch 'therapists/:id',       to: 'therapists#update'
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	respond_to :html, :json
	def index
		urls = %w[http://feeds2.feedburner.com/BpsResearchDigest
              http://daily.psychotherapynetworker.org/feed/
              http://www.apa.org/monitor/monitor-rss.xml
              http://www.apa.org/news/psycport/psycport-rss.xml
              http://feeds.feedburner.com/PsychologyBlog
              http://feeds.socialpsychology.org/psychology-headlines
              http://topics.nytimes.com/top/news/health/diseasesconditionsandhealthtopics/psychology_and_psychologists/index.html?rss=1
              http://www.mindful.org/rss]
		@feeds = Feedjira::Feed.fetch_and_parse urls
	end

	def show
		@title = params[:title]
		@link  = params[:url]

		if current_user.is_a?(Guest)
			redirect_to articles_path, alert: "Please sign-in to share articles"
		end
	end

	def share
		passed_params = {:title => params[:article_title], :url => params[:article_url], :name => params[:name], :email => params[:email]}
		Resque.enqueue(ShareArticleJob, current_user.id, passed_params)
		redirect_to articles_path, notice: "The article has been shared"
	end
end

app/views/articles/index.html.erb
<% title "Articles" %>
<meta name="Description" content="Therapy Articles, find interesting and up to date articles on the topics that are important to you.">

<div class="row" style="margin-top:20px; height:100%">
  <div class="col-xs-2 hidden-xs">
    <%= image_tag "otdlogo.png"%>
  </div>
  <div class="col-xs-10" style="margin-top:20px">
    <h3>Open Therapist Directory<small> Psychology Articles</small></h3>
      <ul class="list" style="padding-top:0px">
        <% @feeds.each do |feed| %>
          <div class='accordion'>
            <h3><%= feed[1].title %></h3>
            <div>
              <% feed[1].entries[0..9].each do |entry| %>
                <ul class='list-group' style='margin:5px'>
                  <li class='list-group-item'><%= link_to entry.title.html_safe.truncate(70), entry.url %> <%= link_to "Share this", articles_show_path(:title => entry.title.html_safe, :url => entry.url), style: 'float:right', class: 'share-link' %></li>
                </ul>
              <% end %>
            </div>
        <% end %>
      </ul>
      <br/><p>Have a suggestion for a journal or RSS feed to include here? <%=link_to "Contact Us", contact_path %></p>
  </div>
</div>

<script>
  $( ".accordion" ).accordion({
    header: "h3",
    collapsible: true,
    active: false,
    heightStyle: 'content'
  });
</script>

<script type="text/javascript" src="/assets/listing.js"></script>

app/views/articles/show.html.erb
<% title "Share Article" %>
<div class="container">
  <div class="row text-center">
  	<div class="col-xs-12">
      <h2 class="title">Share Article: <%= @title %></h2>
      <hr/>
    </div>
  </div>
  <div class="row" style="height:70%">
    <div class="col-xs-6 col-xs-offset-3">
      <%= bootstrap_form_tag url: '/articles/share' do |f| %>
        <%= f.text_field :name, label: "Friend's Name" %>
        <%= f.text_field :email, label: "Friend's Email" %>
        <%= hidden_field_tag 'article_title', @title %>
        <%= hidden_field_tag 'article_url', @link %>
        <%= f.submit "Send Article" %>
      <% end %>
    </div>
  </div>
</div>
<script>
$("#share-form").validate({
	rules: {
		name: "required",
		email: {
			required: true,
			email: true
		},
	},
});

</script>