config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => 'registrations' }
  root 'home#index'
  mount Resque::Server.new, at: "/resque"

  namespace :api do
    namespace :v1 do
      get 'facilities',         to: 'facilities#index',          as: 'facilities', defaults: {format: :json}
      get 'facilities/:id',     to: 'facilities#show',           as: 'facility', defaults: {format: :json}
      get 'therapists',         to: 'therapists#index',          as: 'therapists', defaults: {format: :json}
      get 'therapists/:id',     to: 'therapists#show',           as: 'therapist', defaults: {format: :json}
    end
  end

  namespace :admin do
  	get 'dashboard',            to: 'dashboard#show',            as: 'dashboard'

    get 'facilities',           to: 'facilities#index',          as: 'facilities'
    post 'facilities',          to: 'facilities#import',         as: 'import_facilities'

    get 'therapists',           to: 'therapists#index',          as: 'therapists'
    get 'therapists/:id',       to: 'therapists#show',           as: 'therapist'
    post 'therapists/:id/toggle', to: 'therapists#toggle'
  end

  get  'facilities',            to: 'facilities#index',          as: 'facilities'
  get  'facilities/:id',        to: 'facilities#show',           as: 'facility'
  get  'facilities/share/:id',  to: 'facilities#share_facility', as: 'share_facility'
  post 'facilities/share',      to: 'facilities#share',          as: 'facilities_share'
  post 'facility/save/:id',     to: 'facilities#save_facility',  as: 'save_facility'
  post 'facility/remove/:id',   to: 'users#remove_facility',     as: 'remove_facility'

  get  'contact',               to: 'home#contact',              as: 'contact'
  post 'contact',               to: 'home#send_contact',         as: 'contact_us'
  get  'sign_in',               to: 'home#sign_in',              as: 'sign_in'

  get  'user',                  to: 'users#show',                as: 'user'

  get  'articles',              to: 'articles#index',            as: 'articles'
  get  'articles/share/:title', to: 'articles#show',             as: 'articles_show'
  post 'articles/share',        to: 'articles#share',            as: 'articles_share'

  get  'therapists',            to: 'therapists#index',          as: 'therapists'
  get  'therapists/new',        to: 'therapists#new',            as: 'new_therapist'
  get  'therapists/:id',        to: 'therapists#show',           as: 'therapist'
  delete 'therapists/:id',      to: 'therapists#destroy'
  get  'therapists/:id/edit',   to: 'therapists#edit',           as: 'edit_therapist'
  post 'therapist/save/:id',    to: 'therapists#save_therapist', as: 'save_therapist'
  post 'therapist/remove/:id',  to: 'users#remove_therapist',    as: 'remove_therapist'
  post 'therapists',            to: 'therapists#create'
  patch 'therapists/:id',       to: 'therapists#update'
end

app/views/partials/_footer.html.erb
<footer style='margin-top:20px'>
  <div class="text-left">
  	<div class="col-xs-12">
      © Ian Andersen 2014-2015. |
      <%= link_to "Terms and Conditions", asset_path("otd-terms-and-conditions.pdf") %> |
      <%= link_to "Privacy Statement", asset_path("otd-privacy-statement.pdf") %>
    </div>
	</div>
</footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default">
  <div class='container-fluid'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Open Therapist Directory</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Find a Therapist", therapists_path %></li>
        <% if !current_user.therapist %>
          <li><%= link_to "List Your Practice", new_therapist_path %></li>
        <% else %>
          <li><%= link_to "Edit Your Practice", edit_therapist_path(current_user.therapist.id) %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Resources<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Mental Health Resources", facilities_path %></li>
            <li><%= link_to "Articles", articles_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user.is_a?(User) %>
          <li><%= link_to "Signed in as #{current_user.name}", user_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete, :id => 'sign-out' %></li>
          <% if current_user.role == 'admin' %>
            <li><%= link_to "Admin Dashboard", admin_dashboard_path %></li>
          <% end %>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sign Up/Login<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Sign Up", new_user_registration_path%></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter), :class => 'twitter-auth'%></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div> <!-- container fluid -->
</nav>

<div class='ajax_flash_messages'>
  <% flash.each do |type, message| %>
    <div class="flash" id="<%= type %>">
      <%= message %>
    </div>
  <% end %>
</div>