config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => 'registrations' }
  root 'home#index'
  mount Resque::Server.new, at: "/resque"

  namespace :api do
    namespace :v1 do
      get 'facilities',         to: 'facilities#index',          as: 'facilities', defaults: {format: :json}
      get 'facilities/:id',     to: 'facilities#show',           as: 'facility', defaults: {format: :json}
      get 'therapists',         to: 'therapists#index',          as: 'therapists', defaults: {format: :json}
      get 'therapists/:id',     to: 'therapists#show',           as: 'therapist', defaults: {format: :json}
    end
  end

  namespace :admin do
  	get 'dashboard',            to: 'dashboard#show',            as: 'dashboard'

    get 'facilities',           to: 'facilities#index',          as: 'facilities'
    post 'facilities',          to: 'facilities#import',         as: 'import_facilities'

    get 'therapists',           to: 'therapists#index',          as: 'therapists'
    get 'therapists/:id',       to: 'therapists#show',           as: 'therapist'
    post 'therapists/:id/toggle', to: 'therapists#toggle'
  end

  get  'facilities',            to: 'facilities#index',          as: 'facilities'
  get  'facilities/:id',        to: 'facilities#show',           as: 'facility'
  get  'facilities/share/:id',  to: 'facilities#share_facility', as: 'share_facility'
  post 'facilities/share',      to: 'facilities#share',          as: 'facilities_share'
  post 'facility/save/:id',     to: 'facilities#save_facility',  as: 'save_facility'
  post 'facility/remove/:id',   to: 'users#remove_facility',     as: 'remove_facility'

  get  'contact',               to: 'home#contact',              as: 'contact'
  post 'contact',               to: 'home#send_contact',         as: 'contact_us'
  get  'sign_in',               to: 'home#sign_in',              as: 'sign_in'

  get  'user',                  to: 'users#show',                as: 'user'

  get  'articles',              to: 'articles#index',            as: 'articles'
  get  'articles/share/:title', to: 'articles#show',             as: 'articles_show'
  post 'articles/share',        to: 'articles#share',            as: 'articles_share'

  get  'therapists',            to: 'therapists#index',          as: 'therapists'
  get  'therapists/new',        to: 'therapists#new',            as: 'new_therapist'
  get  'therapists/:id',        to: 'therapists#show',           as: 'therapist'
  delete 'therapists/:id',      to: 'therapists#destroy'
  get  'therapists/:id/edit',   to: 'therapists#edit',           as: 'edit_therapist'
  post 'therapist/save/:id',    to: 'therapists#save_therapist', as: 'save_therapist'
  post 'therapist/remove/:id',  to: 'users#remove_therapist',    as: 'remove_therapist'
  post 'therapists',            to: 'therapists#create'
  patch 'therapists/:id',       to: 'therapists#update'
end

app/models/user.rb
class User < ActiveRecord::Base
  serialize :saved_facilities, Array
  serialize :saved_therapists, Array
  devise :database_authenticatable, :async, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
				 :omniauthable, :omniauth_providers => [:twitter]

  has_one :therapist

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.uid+"@twitter.com",
                            password:Devise.friendly_token[0,20],
                          )
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		if current_user.is_a?(User)
			@user = User.find(current_user.id)
			@saved_facilities = @user.saved_facilities.map do |id|
				Facility.find(id)
			end
      @saved_therapists = @user.saved_therapists.map do |id|
        Therapist.find(id)
      end
		else
			flash[:alert] = "Please sign in first"
			redirect_to root_path
		end
	end

	def remove_facility
		current_user.saved_facilities.delete(params[:id])
		current_user.save
		@facility_id = params[:id]

		respond_to do |format|
      format.js { @facility_id }
    end
	end

  def remove_therapist
    current_user.saved_therapists.delete(params[:id])
    current_user.save
    @therapist_id = params[:id]

    respond_to do |format|
      format.js { @therapist_id }
    end
  end
end

app/views/users/remove_facility.js.erb
$("#facility_<%= @facility_id %>").remove();
$("#remove_facility_<%= @facility_id%>").remove();

app/views/users/remove_therapist.js.erb
$("#therapist_<%= @therapist_id %>").remove();
$("#remove_therapist_<%= @therapist_id%>").remove();

app/views/users/show.html.erb
<% title "User" %>
<div class="container">
  <div class="row">
    <div class="col-xs-12 text-center">
      <h2><%= @user.name %></h2><hr/>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class='accordion'>
        <h3>My Saved Facilities</h3>
          <div>
            <% @saved_facilities.each do |facility| %>
              <p id="facility_<%= facility.id %>"><%= link_to facility.name1, facility_path(facility.id) %>
                <%= form_tag(remove_facility_path(facility.id), remote: true) do %>
                <%= submit_tag 'remove', class: "button tiny", id: "remove_facility_#{facility.id}" %>
                <% end %>
              </p><br/>
            <% end %>
          </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class='accordion'>
        <h3>My Saved Therapists</h3>
          <div>
            <% @saved_therapists.each do |therapist| %>
              <p id="therapist_<%= therapist.id %>"><%= link_to therapist.full_name, therapist_path(therapist.id) %>
                <%= form_tag(remove_therapist_path(therapist.id), remote: true) do %>
                <%= submit_tag 'remove', class: "button tiny", id: "remove_therapist_#{therapist.id}" %>
                <% end %>
              </p><br/>
            <% end %>
          </div>
      </div>
    </div>
  </div>
</div>

<script>
	$( ".accordion" ).accordion({
    header: "h3",
    collapsible: true,
    active: false
  });
</script>