config/routes.rb
require 'resque/server'

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks", :registrations => 'registrations' }
  root 'home#index'
  mount Resque::Server.new, at: "/resque"

  namespace :api do
    namespace :v1 do
      get 'facilities',         to: 'facilities#index',          as: 'facilities', defaults: {format: :json}
      get 'facilities/:id',     to: 'facilities#show',           as: 'facility', defaults: {format: :json}
      get 'therapists',         to: 'therapists#index',          as: 'therapists', defaults: {format: :json}
      get 'therapists/:id',     to: 'therapists#show',           as: 'therapist', defaults: {format: :json}
    end
  end

  namespace :admin do
  	get 'dashboard',            to: 'dashboard#show',            as: 'dashboard'

    get 'facilities',           to: 'facilities#index',          as: 'facilities'
    post 'facilities',          to: 'facilities#import',         as: 'import_facilities'

    get 'therapists',           to: 'therapists#index',          as: 'therapists'
    get 'therapists/:id',       to: 'therapists#show',           as: 'therapist'
    post 'therapists/:id/toggle', to: 'therapists#toggle'
  end

  get  'facilities',            to: 'facilities#index',          as: 'facilities'
  get  'facilities/:id',        to: 'facilities#show',           as: 'facility'
  get  'facilities/share/:id',  to: 'facilities#share_facility', as: 'share_facility'
  post 'facilities/share',      to: 'facilities#share',          as: 'facilities_share'
  post 'facility/save/:id',     to: 'facilities#save_facility',  as: 'save_facility'
  post 'facility/remove/:id',   to: 'users#remove_facility',     as: 'remove_facility'

  get  'contact',               to: 'home#contact',              as: 'contact'
  post 'contact',               to: 'home#send_contact',         as: 'contact_us'
  get  'sign_in',               to: 'home#sign_in',              as: 'sign_in'

  get  'user',                  to: 'users#show',                as: 'user'

  get  'articles',              to: 'articles#index',            as: 'articles'
  get  'articles/share/:title', to: 'articles#show',             as: 'articles_show'
  post 'articles/share',        to: 'articles#share',            as: 'articles_share'

  get  'therapists',            to: 'therapists#index',          as: 'therapists'
  get  'therapists/new',        to: 'therapists#new',            as: 'new_therapist'
  get  'therapists/:id',        to: 'therapists#show',           as: 'therapist'
  delete 'therapists/:id',      to: 'therapists#destroy'
  get  'therapists/:id/edit',   to: 'therapists#edit',           as: 'edit_therapist'
  post 'therapist/save/:id',    to: 'therapists#save_therapist', as: 'save_therapist'
  post 'therapist/remove/:id',  to: 'users#remove_therapist',    as: 'remove_therapist'
  post 'therapists',            to: 'therapists#create'
  patch 'therapists/:id',       to: 'therapists#update'
end

app/models/facility.rb
class Facility < ActiveRecord::Base
  require 'csv'

  def address
    "#{location_street1} #{location_street2}, #{location_city}, #{location_state} #{location_zip}"
  end

  def website?
    if website
      website
    else
      "None Provided"
    end
  end

  def intake
    if intake1
      intake1
    elsif intake2
      intake2
    else
      "None Provided"
    end
  end

  def hotline
    if hotline1
      hotline1
    elsif hotline2
      hotline2
    else
      "None Provided"
    end
  end

  def services
    ("<li>" + self.services_text1.to_s + "</li><li>" + self.services_text2.to_s + "</li><li>" + self.services_text3.to_s + "</li><li>" + self.services_text4.to_s + "</li><li>" + self.services_text5.to_s + "</li><li>" + self.services_text6.to_s + "</li><li>" + self.services_text7.to_s + "</li>").gsub(/;/, "").html_safe
  end

  def json_services
    (self.services_text1.to_s + self.services_text2.to_s + self.services_text3.to_s + self.services_text4.to_s + self.services_text5.to_s + self.services_text6.to_s + self.services_text7.to_s)
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true, encoding: "iso-8859-1:UTF-8") do |row|
      facility_hash = row.to_hash

      facility = Facility.where(name1: facility_hash["name1"])

      if facility.count == 1
        facility.first.update_attributes(facility_hash)
      else
        Facility.create!(facility_hash)
      end
    end
  end

end

app/controllers/admin/facilities_controller.rb
class Admin::FacilitiesController < Admin::BaseController
	def index

	end

	def import
	  Facility.import(params[:file])
	  redirect_to root_url
	end
end

app/controllers/api/v1/facilities_controller.rb
class Api::V1::FacilitiesController < API::V1::BaseController
	respond_to :json

	def index
		render json: { facility: all_formatted }
	end

	def show
		@facility = Facility.find(params[:id])

		render json: { facility: format_facility(@facility) }
	end

  private

  def all_formatted
    Facility.all.map do |facility|
      returned_facility(facility)
    end
  end

  def format_facility(facility)
    returned_facility(facility)
  end

  def returned_facility(facility)
    {
      'id' => facility.id,
      'name' => facility.name1,
      'website' => facility.website,
      'phone' => facility.phone,
      'intake' => facility.intake1,
      'hotline' => facility.hotline1,
      'address' => "#{facility.location_street1} #{facility.location_street2}, #{facility.location_city}, #{facility.location_state} #{facility.location_zip}",
      'services' => facility.json_services
    }
  end



end

app/controllers/facilities_controller.rb
class FacilitiesController < ApplicationController
	respond_to :html

	def index
    all_facilities = Facility.all
		@first_facilities = all_facilities[0..20].to_json.html_safe
		@facilities ||= all_facilities.to_json.html_safe
		@states     ||= StateHelper.state_list
	end

	def show
		@facility = Facility.find(params[:id])
	end

	def share_facility
		if current_user.is_a?(Guest)
			redirect_to facilities_path, alert: "Please sign-in to share facilities"
		end
		@facility = Facility.find(params[:id])
	end

	def save_facility
		if current_user.is_a?(User)
  		respond_to do |format|
  			if !current_user.saved_facilities.include?(params[:id])
  			 	current_user.saved_facilities << params[:id]
  			 	current_user.save!
  			end
       	format.js{render layout: false}
     	end
    end
	end

	def share
		passed_params = {:facility_id => params[:facility_id], :name => params[:name], :email => params[:email]}
		Resque.enqueue(ShareFacilityJob, current_user.id, passed_params)
		redirect_to facility_path(params[:facility_id]), notice: "This Facility has been shared successfully"
	end
end

app/views/facilities/index.html.erb
<% title "Facility Finder" %>
<head>
  <script src="https://maps.googleapis.com/maps/api/js?signed_in=true&libraries=geometry&key=AIzaSyCB5IfaUUgXXtsuZNdCzF-H_MVsBLmw64M"></script>
  <meta name="Description" content="Find a mental health facility near you. Free for clients. Free for therapists.">
</head>

<div class="container">
  <div class="row">
    <div class="col-md-2">
      <div>
        <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" class='donate'>
          <input type="hidden" name="cmd" value="_s-xclick">
          <input type="hidden" name="hosted_button_id" value="YGJNNCN8FP668">
          <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
          <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
        </form>
      </div>
      <%= image_tag "otdlogo.png", class: 'hidden-xs hidden-sm'%>
    </div>
    <div class="col-md-7 col-md-offset-2" style='margin-top:20px'>
      <h2>Open Therapist Directory<small> Facility Finder</small></h2>
      <div style='text-align:right; margin-top:-30px'>
        <% if !current_user %>
          <small class='sign-in-index'>Sign in to save facilities to your list.</small>
        <% else %>
          <small><%= link_to "My Saved Facilities", user_path %></small>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 col-xs-6">
      <p style="display:inline-block">State:</p>
      <form action="" style="display:inline-block">
        <select name="filter-state" id="filter-state" class="form-control">
          <% @states.each do |state| %>
            <option value="<%=state%>"><%=state%></option>
          <% end %>
        </select>
      </form>
    </div>
    <div class="col-md-4 col-xs-6">
      <small style="float:right">Click on the plus icon to add the location to the map.</small>
    </div>
  </div>
  <hr/>
  <div class="row">
    <div class="col-xs-12 col-md-3">
      <ul class="list-unstyled">
        <div class="col-xs-12">
          <li><input class="search" placeholder="Search All Fields" style="width:100%" /></li><hr/>
        </div>
        <div class="row">
          <div class="col-xs-6">
            <li><span class="sort" data-sort="name" style="display:inline-block">Sort by Name</span></li>
          </div>
          <div class="col-xs-6">
            <li><span class="sort" data-sort="city" style="display:inline-block">Sort by City</span></li>
          </div>
        </div>
        <hr/>
        <div class="hidden-xs">
          <li><input type="checkbox" class="check" data-check="spanish"/> Español Habla</input></li>
          <li><input type="checkbox" class="check" data-check="medicaid"/> Medicaid</input></li>
          <li><input type="checkbox" class="check" data-check="medicare"/> Medicare</input></li>
          <li><input type="checkbox" class="check" data-check="substance"/> Substance Abuse</input></li>
          <li><input type="checkbox" class="check" data-check="lgbt"/> LGBT Services</input></li>
          <span id="return-check"></span>
          <li><input type="checkbox" class="check" data-check="veterans"/> Veteran Services</input></li><hr>
          <p id="distance"></p>
          <div id="map-canvas" style="width:400px; height:400px;"></div>
          <!-- OTD-Therapist Index -->
          <ins class="adsbygoogle"
               style="display:inline-block;width:300px;height:250px"
               data-ad-client="ca-pub-3222712415808754"
               data-ad-slot="8483377423">
          </ins>
        </div>
      </ul>
    </div>
    <div class="col-xs-12 col-md-8 col-md-offset-1">
      <ul class="list" style="padding-top:0px"></ul>
    </div>
  </div>
  <div class="col-xs-12 hidden-sm">
    <ins class="adsbygoogle"
     style="display:inline-block;width:320px;height:100px"
     data-ad-client="ca-pub-3222712415808754"
     data-ad-slot="4269197028"></ins>
  </div>
</div> <!-- container -->
  <script type="text/javascript" src="/assets/listing.js"></script>
  <script type="text/javascript" src="/assets/maps.js"></script>
<script>

  var initialState = 'AK'
  var facilities = <%= @facilities %>
  var firstFacilities   = <%= @first_facilities %>
  var currentFacilities = firstFacilities;
  var state = $('#filter-state').val();

  _.each(firstFacilities, render);

  setInitialState(initialState);

  addFacility();

  var geocoder = new google.maps.Geocoder();

  var initialLocation = navigator.geolocation.getCurrentPosition(function (position) {
       initialLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
       map.setCenter(initialLocation);

       var marker = new google.maps.Marker({
          position: initialLocation,
          title: 'Your Location',
          draggable: false,
          map: map
      });

      map.setCenter(marker.getPosition());
  });

  var mapOptions = {
    center: initialLocation,
    zoom: 12
  };

  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);

  google.maps.event.addDomListener(window, 'load');

  function setDistance(resultLocation) {
    var distance = google.maps.geometry.spherical.computeDistanceBetween (initialLocation, resultLocation);
    var toMiles = 0.000621371;
    var distanceInMiles = Math.round(distance * toMiles);
    $('#distance').empty();
    $('#distance').append("Distance to facility: " + distanceInMiles + " Miles");
  }

  function addMarker(address) {
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        map.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
        });
        var resultLocation = results[0].geometry.location;

        setDistance(resultLocation);

        marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png')
      } else {
        alert('Geocode was not successful for the following reason: ' + status);
      }
    });
  }

</script>

app/views/facilities/save_facility.js.erb
$('.ajax_flash_messages').html("<div class='flash' id='notice'>Facility Saved to Your List</div>");
$('.flash').delay(2000).fadeOut(800);

app/views/facilities/share_facility.html.erb
<div class="container">
	<div class="row text-center">
    <div class="col-xs-12">
      <h2 class="title">Share Facility: <%= @facility.name1 %></h2>
      <hr/>
    </div>
  </div>
  <div class="row" style="height:70%">
    <div class="col-xs-6 col-xs-offset-3">
      	<%= bootstrap_form_tag url: '/facilities/share' do |f| %>
				  <%= f.text_field :name, label: "Friend's Name" %>
				  <%= f.text_field :email, label: "Friend's Email" %>
				  <%= hidden_field_tag 'facility_id', @facility.id %>
				  <%= f.submit "Send", id: 'send-button' %>
				<% end %>
      </div>
    </div>
</div>

<script>
  $("#share-form").validate({
  	rules: {
  		name: "required",
  		email: {
  			required: true,
  			email: true
  		},
  	},
  });
</script>

app/views/facilities/show.html.erb
<% title "Facility Information" %>
<div class="container">
  <div class="row">
  	 <div class="col-xs-12 text-center" style="margin-top:20px">
  		<h2><%= @facility.name1 %></h2>
    </div>
  </div>
  <hr/>
  <div class="row">
    <div class="col-xs-12">
  	  <p><b>Website:</b> <%= @facility.website? %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
  		<p><b>Phone:</b> <%= @facility.phone %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
  		<p><b>Intake:</b> <%= @facility.intake %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
  		<p><b>Hotline:</b> <%= @facility.hotline %></p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
  		<p><b>Address:</b> <%= @facility.address %></p>
    </div>
  </div>
  	<p><b>Services:</b><ul> <%= @facility.services %></ul></p>
  	<p>	<%= link_to "Share this", share_facility_path(:id => @facility.id) %></p>
</div>